################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
# for OPS-243 device, see
#   https://nodered.org/docs/getting-started/docker#serial-port---dialout---adding-groups 
################################################################################
services:
  node-red:
    container_name: nodered
    restart: unless-stopped
    build: . 
    ports:
      - "1880:1880"
      - "1883:1883"
    volumes:
      - ~/code/nodered/data:/data
    devices:
      - "/dev/ttyACM0"
    group_add:
      - dialout
    environment:
      NODE_RED_CREDENTIAL_SECRET: ""
      NODE_RED_ENABLE_PROJECTS: true
      NODE_RED_ENABLE_SAFE_MODE: false
      VAR_LOCATION: "ne26th-wasco-sb-01"
      VAR_RADAR_CAMERA: "picam_h264"
      VAR_INFLUXDB_BUCKET: "influxdb_bucket"
    depends_on:
      frigate:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      mongo:
        condition: service_started