################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
# for OPS-243 device, see
#   https://nodered.org/docs/getting-started/docker#serial-port---dialout---adding-groups 
#
# disable volumes for data when deploying to allow image to be built with all packages
################################################################################
services:
  node-red:
    container_name: nodered
    restart: unless-stopped
    build: .
    ports:
      - "1880:1880"                     #node-red flow gui and dashboard ui port
      - "1883:1883"                     #aedes mqtt broker port 
    volumes:
    #  - ~/code/nodered/data:/data      # uncomment for dev deployment 
      - ~/code/nodered/db:/db           # internal sqlite db 
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/ttyACM0"
    group_add:
      - dialout
    environment:
      TZ: America/Los_Angeles
      NODE_RED_CREDENTIAL_SECRET: "myNodeRED1234"
      NODE_RED_ENABLE_PROJECTS: true
      NODE_RED_ENABLE_SAFE_MODE: false
      VAR_LOCATION: "ne26th-wasco-sb-01"
      VAR_RADAR_CAMERA: "picam_h264"
      VAR_INFLUXDB_ORG: "taffic_monitor_01"
      VAR_INFLUXDB_BUCKET: "influxdb_bucket"
      VAR_EVENTS_DB: "tmdb"
      VAR_EVENTS_TABLE: "events"
      VAR_MQTT_USER: "mqtt_user"        #broker settings
      VAR_MQTT_PASS: "mqtt_pass"        #broker settings
    depends_on:
      frigate:
        condition: service_healthy
      influxdb:
        condition: service_healthy