mqtt:
  enabled: false
  # Required: host name
  host: 10.10.10.223
  # Optional: port (default: shown below)
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

cameras:
  picam_h264: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://10.10.10.223:8554/picam_h264
        roles:
        - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 2304 # <---- update for your camera's resolution
      height: 1296 # <---- update for your camera's resolution
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    zones:
      zone_far:
        coordinates: 1248,556,926,497,231,657,477,769
      zone_near:
        coordinates: 1690,695,1355,563,429,754,825,982
    motion:
      mask:
      - 0,419,0,0,889,0,1083,0,2019,0,1982,270,1094,306
    objects:
      filters:
        car:
          mask:
          - 0,320,0,0

  picam_gs_h264: # <------ Name the camera
    enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://10.10.10.223:8554/picam_gs_h264
        roles:
        - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1456 # <---- update for your camera's resolution
      height: 1088 # <---- update for your camera's resolution
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    zones:
      zone_far:
        coordinates: 1137,444,0,67,0,876
      zone_near:
        coordinates: 1456,1088,1456,539,1215,462,0,880,0,1088

  unifi-cam-pi-replica:
    enabled: false
    ffmpeg:
      inputs:
      - path: rtsps://10.10.10.1:7441/ec9Y7Ls0rz6yLaIg?enableSrtp
        roles:
        - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5

objects:
  track:
  - bicycle
  - person
  - car
  - motorcycle
  - dog

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 21
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  crop: true
  retain:
    default: 60
