################################################################################
# InfluxDB Compose
################################################################################
# setup at https://hub.docker.com/_/influxdb
# Environment variables:
# DOCKER_INFLUXDB_INIT_MODE: "setup"
# DOCKER_INFLUXDB_INIT_USERNAME: "my-user" # The username to set for the system's initial super-user (Required).
# DOCKER_INFLUXDB_INIT_PASSWORD: "my-password" # The password to set for the system's inital super-user (Required).
# DOCKER_INFLUXDB_INIT_ORG: "my-org" # The name to set for the system's initial organization (Required).
# DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket" # The name to set for the system's initial bucket (Required).
# DOCKER_INFLUXDB_INIT_RETENTION: ""  # The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.
# DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "my-super-secret-auth-token" # The authentication token to associate with the system's initial super-user. If not set, a token will be auto-generated by the system.
################################################################################
version: "3.9"
services:
  influxdb:
    container_name: influxdb
    restart: unless-stopped 
    image: influxdb:2.7.5
    volumes:
      - ~/code/influxdb/data:/var/lib/influxdb2
      - ~/code/influxdb/config:/etc/influxdb2  
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influxdb_user"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influxdb_pass"
      DOCKER_INFLUXDB_INIT_ORG: "taffic_monitor_01"
      DOCKER_INFLUXDB_INIT_BUCKET: "influxdb_bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influxdb_admin_token"